version: '3.9'

services:
  database:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - ./database:/var/lib/mysql:r
    user: '501'
    networks:
      - 03--user-management

  backend:
    depends_on:
      - database
#    image: the0ffh/03-user-management-backend:0.0.4
    build: .
    environment:
      NODE_ENV: 'development'
      MYSQL_DATABASE: devdb
      MYSQL_DATABASE_HOST: database
      MYSQL_DATABASE_PORT: 3306
      MYSQL_USER: dev
      MYSQL_PASSWORD: devpw
      MYSQL_ROOT_PASSWORD: root
      SERVER_PORT: 3000
      SERVER_API_PATH: path
      SERVER_OPENAPI_PATH: openapi
    ports:
      - 3000:3000
    networks:
      - 03--user-management

networks:
  03--user-management:
    name: 03--user-management
    driver: bridge
