version: '3.9'

services:
  database:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - ./database:/var/lib/mysql:r
    user: '501'

# user: $UID - use with colima in order to utilize volume mounts
