name: pull request
on:
  pull_request


jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: 'v18.14.1'
      - run: yarn
      - run: yarn lint
      - run: yarn test:ts
      - run: yarn test
      - run: yarn test:cov
      - run: yarn test:e2e
